### ISSUE TITLE
Identity-based Signature (SignID)

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#2]
## Brief

CryptID.native supports Identity-based Encryption. However, we should consider adding other identity-based schemes using on top of the facilities provided by the existing codebase.

## Task

Implement Identity-based Signature (named SignID).

**Comment by BeardOfDoom** [comment]
The Identity-based Signature is implemented, namely the Hess-IBS. The `enhancement/identity-based-signature-signid-#2` branch was merged to master. The last commit related to this issue is f2d4a7e0d6ae36430e7cf90017d180c64cef7a81 .
