### ISSUE TITLE
Rename the endpoint functions

### ISSUE THREAD

**Issue by BeardOfDoom** [cryptid-org/cryptid-native#22]
The current endpoint function names are designed only for Identity-based Cryptography, but since other features are under construction, we should consider renaming the endpoints.

Requirements:
- Make the new name flexible enough for more different "features" under the same domain
- Support multiple scheme implementation of the same "feature" (multiple IBE implementation for example"

@battila7 @bombifighter this will affect the interoperability and possibly the JS API layers too.

**Comment by BeardOfDoom** [comment]
Investigated the issue. The following refactor required on the native-side.

- Create naming conventions for the feature algorithms and feature structures.
- Create unique public parameters and ciphertext and signature structures for every scheme, since most of them are not similar. (This might result in code redundancy, need to be discussed).
- Move HashFunction to util.
- SecurityLevel is a global parameter in my opinion in Elliptic-curve Cryptography, so it needs to be moved too.

**Comment by battila7** [comment]
As labelled, this change would completely break our public interface. Thus, a major version bump will be required.

Changes in clients that we control (CryptID.js for now) will be further discussed.

**Comment by battila7** [comment]
Also, I suggest to use this issue as an opportunity to reorder/rename function parameters for ease of use. If we have to break the public API, then we are free to do what we want (sort of) :)

**Comment by battila7** [comment]
Kinda overlaps with #41, please specify more precisely @BeardOfDoom

**Comment by BeardOfDoom** [comment]
The lower level function names scheme is `module_camelCase` as specified in issue #41. But for the endpoint functions I propose the `cryptid_feature_camelCase` scheme.

Example:

`cryptid_bfibe_setup`

@battila7 Opinion?

**Comment by battila7** [comment]
That's nice, but I would go for an even more granular approach, like

`cryptid_ibe_bf_setup`

In my opinion this would support IBE schemes other than BF better.

**Comment by battila7** [comment]
Closing as #55 is merged.
