### ISSUE TITLE
Unclear display of the memory check

### ISSUE THREAD

**Issue by BeardOfDoom** [cryptid-org/cryptid-native#31]
In the Azure pipeline, there is the use of Valgrind as a memory checking tool, but it gives a mess as an output in the command line. It would be helpful if there would be a more readable output.

**Comment by battila7** [comment]
Valgrind XML output is now accessible as an Azure artifact as of #32

**Comment by battila7** [comment]
Also, HTML output is now generated by [parsegrind](https://github.com/cryptid-org/parsegrind) on CI as of #38
