### ISSUE TITLE
Non-uniform random generators

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#36]
As pointed out in #34 our random generator routines cannot be considered uniform (given that they are working with a uniform source).

Even though there are minor differences regarding the probabilities of the generated numbers, we should not ignore this issue.

**Comment by peteroupc** [comment]
See also briansmith/ring#942 for a related discussion involving generation of [random integers](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#RNDINT_Random_Integers_in_0_N) in a range (rejection sampling vs. reduction), and also what I wrote in [this section](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#Security_Considerations).

**Comment by BeardOfDoom** [comment]
Thank you for your response @peteroupc . I chose to implement the rejection sampling method, which seems to be good enough in our case.

**Comment by battila7** [comment]
@peteroupc Thanks for the very informative response! Also, the articles you have on your website are great!

**Comment by battila7** [comment]
Can be closed once #37 is merged.

**Comment by battila7** [comment]
Closing as #37 is merged.
