### ISSUE TITLE
Uniform function parameter ordering and naming.

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#41]
## Task

Uniformize the following across the library, especially the public API:
  * function naming scheme,
  * function parameter naming scheme,
  * function parameter order.

### Function naming scheme

Make sure, that the following scheme is applied:

`module_camelCase`

### Function parameter order

  * out parameters,
  * in/out parameters,
  * in parameters.

**Comment by BeardOfDoom** [comment]
The `complexAffine_infinity` function is a special case, will deal with it in issue #5.

**Comment by battila7** [comment]
Closing as #57 is merged.
