### ISSUE TITLE
Remove the shared validation header and source

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#56]
## Brief

The validation header is getting much bulkier than it should be by gaining lots of functionality from across modules. 

## Task

Removed the shared validation routines and place separate validation related stuff into the separate modules.

Only prime testing should stay in the common utils directory. 

## Notes

Make sure, that the prime testing implementation can be swapped out for an extern one.

**Comment by BeardOfDoom** [comment]
Also just noticed that there is no validation of the HashFunction implemented. Is should be a TODO in this issue.
