### ISSUE TITLE
Reimplement complex_multiplicativeInverse

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#7]
## Brief

Multiplicative inverse calculation for Complex instances is some handcrafted black magic stuff performing an unnecessary amount of calls. This is quite bad, since multiplicative inverse is needed for many other operations.

## Task

Write a better (more performant and easier to undersant) implementation of Complex multiplicative inverse.

**Comment by BeardOfDoom** [comment]
Implemented the standard complex multiplicative inverse function, and added to the repository in commit: https://github.com/cryptid-org/cryptid-native/commit/c01f81ed17f9210bcb32476250e2e0a47325d197 .
