### ISSUE TITLE
Resolve pipeline test/coverage redundancy

### ISSUE THREAD

**Issue by battila7** [cryptid-org/cryptid-native#9]
## Brief

Our current pipeline contains separate steps for producing test results and test coverage, despite the fact that both requires running the test executables. 

## Task

Modify the `coverage` task.js command so that it generates both test result XMLs and LCOV coverage.

**Comment by battila7** [comment]
Resolved by #33.

**Comment by BeardOfDoom** [comment]
This impovement caused a bug of task.sh. The `task.sh test` command fails to run with error

> gcc: error: undefined: No such file or directory

It works only if I use the `--coverage` switch too.

**Comment by battila7** [comment]
PR submitted to fix this issue: #35 

Nice catch, I forgot regression testing. Shame.

**Comment by battila7** [comment]
Closing as #35 is merged.
